apiVersion: v2
name: cowsay
description: A Helm chart for Flask application with PostgreSQL
type: application
version: 1.0.1
appVersion: "1.0.1"

dependencies:
  - name: postgresql
    version: 16.7.4       
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
