# logging/fluent-bit/fluent-bit.yaml
# UPDATED VERSION - Fixed to use DaemonSet with proper volume mounts
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fluent-bit
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    chart: fluent-bit
    targetRevision: 3.1.5
    helm:
      releaseName: fluent-bit
      values: |
        # Enable DaemonSet instead of Deployment
        daemonset:
          enabled: true
        deployment:
          enabled: false
        
        fluentd:
          enabled: false
        rbac:
          create: true
        serviceAccount:
          create: true
          enabled: true
        
        # Mount host paths for log access
        volumeMounts:
          - name: varlog
            mountPath: /var/log
            readOnly: true
          - name: varlibdockercontainers
            mountPath: /var/lib/docker/containers
            readOnly: true
          - name: etcmachineid
            mountPath: /etc/machine-id
            readOnly: true
        
        volumes:
          - name: varlog
            hostPath:
              path: /var/log
          - name: varlibdockercontainers
            hostPath:
              path: /var/lib/docker/containers
          - name: etcmachineid
            hostPath:
              path: /etc/machine-id
              type: File
        
        config:
          service: |
            [SERVICE]
              Daemon Off
              Flush 5
              Log_Level info
              HTTP_Server On
              HTTP_Listen 0.0.0.0
              HTTP_Port 2020

          inputs: |
            [INPUT]
              Name tail
              Path /var/log/containers/*.log
              Tag kube.*
              Parser apache_custom
              Mem_Buf_Limit 50MB
              Skip_Long_Lines On
              Refresh_Interval 10

          filters: |
            [FILTER]
              Name kubernetes
              Match kube.*
              Merge_Log On
              Keep_Log Off
              K8S-Logging.Parser On
              K8S-Logging.Exclude Off

            [FILTER]
              Name grep
              Match kube.*
              Regex kubernetes.container_name ^cowsay$

          outputs: |
            [OUTPUT]
              Name es
              Match kube.*
              Index cowsay-app
              Type _doc
              Host elasticsearch
              Port 9200
              Logstash_Format On
              Logstash_Prefix cowsay-app
              Suppress_Type_Name On
              Retry_Limit 3

          customParsers: |
            [PARSER]
                Name   apache_custom
                Format regex
                Regex  ^(?<remote>[^ ]*) - - \[(?<time>[^\]]*)\] "(?<method>\S+) (?<url>\S+) (?<protocol>[^"]+)" (?<code>\d+) -
                Time_Key time
                Time_Format %d/%b/%Y:%H:%M:%S
  
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true